### ISSUE TITLE
bitcoind: chainparams.cpp:261: CTestNetParams::CTestNetParams(): Assertion failed.

### ISSUE THREAD

**Issue by xdemocle** [BTCPrivate/BTCP-Rebase#12]
After proper compilation of the sources with ./script/build on main folder, I got this error below at first start:
```
➜  BTCP-Rebase git:(master) ./src/bitcoind -debug -noprinttoconsole
bitcoind: chainparams.cpp:261: CTestNetParams::CTestNetParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x0007104ccda289427919efc39dc9e4d499804b7bebc22df55f8b834301260602")' failed.
[1]    8391 abort (core dumped)  ./src/bitcoind -debug -noprinttoconsole
```

**Comment by jc23424** [comment]
Ah, hi, sorry, that is fixed here https://github.com/BTCPrivate/BTCP-Rebase/pull/13

**Comment by xdemocle** [comment]
I tried that patch but after launch and running for a while with no output on terminal, I got what follow:

```
➜  BTCP-Rebase git:(master) ✗ ./src/bitcoind -debug -noprinttoconsole

bitcoind: validation.cpp:2449: bool CChainState::ConnectTip(CValidationState&, const CChainParams&, CBlockIndex*, const std::shared_ptr<const CBlock>&, ConnectTrace&, DisconnectedBlockTransactions&): Assertion `pcoinsTip->GetAnchorAt(pcoinsTip->GetBestAnchor(), oldTree)' failed.
[1]    12675 abort (core dumped)  ./src/bitcoind -debug -noprinttoconsole
```

**Comment by jc23424** [comment]
Hmm, interesting, that was an issue I saw in development for a while, but thought it was fixed. Your logs should be in ~/.btcp/debug.log - what's there?

**Comment by jc23424** [comment]
took a little while to reproduce this (i think its somewhat architecture dependent) but I believe this will fix what you're seeing https://github.com/BTCPrivate/BTCP-Rebase/pull/17
Thanks for reporting!

**Comment by ch4ot1c** [comment]
Still getting this error on a clean Ubuntu build. It happens during the headers-first sync, at block #251993 approx, consistently.

**Comment by ch4ot1c** [comment]
Nvm it works, be sure to `make` and clear datadir with the change integrated.
